### ISSUE TITLE
Upravit disclaimer v Chrome Web Store

### ISSUE THREAD

**Issue by krtek** [realreality/reality-plugin#18]
Dát do Chrome Web Store disclaimer o tom, že chceme permissions ke všem webům, ale nečteme data.

Viz https://chrome.google.com/webstore/detail/punkový-konzument/ebmgejpgpphipjooiopnndkdiciedkdj?utm_source=gmail

> NOTE ABOUT REQUESTED PERMISSIONS:

> This addon requests a permission to access all web pages. Without this permission, I would have to ask for additional permissions every time I add support for another e-shop. That would be very annoying.

> I promise that I don't and won't sniff or modify any other websites than the ones listed above.

**Comment by michalbcz** [comment]
done
