### ISSUE TITLE
Add sreality.cz

### ISSUE THREAD

**Issue by krtek** [realreality/reality-plugin#2]

**Comment by michalbcz** [comment]
Sice se zobrazi, ale kdyz se pohybuje uzivatel uvnitr sreality.cz tak obsah okna widgetu zamrzne s data pro prvne zobrazeny inzerat. Je potreba reagovat na zmenu stranky (ajax).

**Comment by michalbcz** [comment]
Dalsi problem je, ze widget ziska styl ze stranek sreality.cz a je celej vizualne rozhozenej.

**Comment by bedla** [comment]
s tema css jsem vygooglil toto http://stackoverflow.com/questions/15901030/reset-remove-css-styles-for-element-only :-)

**Comment by michalbcz** [comment]
@bedla jj to je spravny reseni...uvazoval jsem o tom ale chci bejt rychlej tak prasim ;)

**Comment by bedla** [comment]
koukal jsem na to sreality ... ten (push|onpop)state nefunguje? https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onpopstate

**Comment by michalbcz** [comment]
@bedla nefungovalo, mozna jsem udelal nekde chybu - zkus to sam :) 

kazdopadne pushstate ma tu nevyhodu, ze to zareagujes jen na zmenu adresy - pokud to nekdo aktualizuje jakkoli jinak tak by to tu zmenu nezachytilo

**Comment by bedla** [comment]
jj uz na to koukam ... to je fakt lame :-) no to tvoje reseni je ok..
