### ISSUE TITLE
podpora analytics

### ISSUE THREAD

**Issue by bedla** [realreality/reality-plugin#22]
zjistovat, kolik lidi aktivne vyuziva plugin

**Comment by krtek** [comment]
@michalbcz Vygeneruješ ID pro Google Analytics? Minule jsi to dělal Ty, ne?

**Comment by michalbcz** [comment]
@krtek bude to muj pondelni ukol :)

**Comment by krtek** [comment]
Pls. rozdělit na dvě GA ID.

**Comment by michalbcz** [comment]
rozdeleno - nove GA nastaveno v Google Extension Developer Dashboard at nemusim prebuildovavat appku
