### ISSUE TITLE
terms and conditions

### ISSUE THREAD

**Issue by bedla** [realreality/reality-plugin#23]
aby bylo jasne, ze pouzivanim souhlasi s tim, ze jim plugin drobne modifikuje html v prohlizeci a ze informace nejsou smerodatne
a ze za nic nebereme zodpovednost :-)
klasicke sw kecy

**Comment by krtek** [comment]
Tohle [už máme](https://chrome.google.com/webstore/detail/real-reality/obkcimklomeknmfjmglfggenjijioenj). Přečti si konec popisu.
