### ISSUE TITLE
Mixed content warning on sreality

### ISSUE THREAD

**Issue by vire** [realreality/reality-plugin#24]
RR Backend runs on `http` and client on sreality is served by default via `https`, and you can't load scripts. That leads to fact that no liftago data is rendered

![image](https://cloud.githubusercontent.com/assets/4021908/19665690/84f15656-9a46-11e6-87d1-7eabb2edbd0a.png)

![image](https://cloud.githubusercontent.com/assets/4021908/19665723/b787caaa-9a46-11e6-8ad0-e93150874a38.png)

**Comment by bedla** [comment]
Backend server is on https now. closing.

**Comment by michalbcz** [comment]
tohle je o liftago api

**Comment by krtek** [comment]
Nevystřelíme to Liftago API definitivně?

**Comment by bedla** [comment]
Jsem pro, až budou mít stabilní api, tak je rádi zaintegrujeme

Dne 29. 10. 2016 2:02 odp. napsal uživatel "Lukáš Marek" <
notifications@github.com>:

**Comment by michalbcz** [comment]
jsem taky pro
