### ISSUE TITLE
Cena za m2 nefunguje na bezrealitky.cz

### ISSUE THREAD

**Issue by krtek** [realreality/reality-plugin#29]
![screen shot](https://cloud.githubusercontent.com/assets/422139/19828775/9ad94316-9dcf-11e6-86ce-44830d843ebb.png)

**Comment by michalbcz** [comment]
vrhnes se na to @vire ? :)

**Comment by vire** [comment]
@michalbcz With pleasure :)

**Comment by michalbcz** [comment]
@vire nice work, thanks as always :)
