### ISSUE TITLE
Tags keep appending

### ISSUE THREAD

**Issue by vire** [realreality/reality-plugin#53]
Steps to reproduce:

1) checkout latests revision of *master* 8b3e79878863b4dfe13506d30343b877c36390fc
2) go to sreality and choose listing
3) to through multiple (3-5) properties which have tags
4) tags keeps appending to the `tags` element but aren't removed

Screenshots: 

![image](https://cloud.githubusercontent.com/assets/4021908/20467126/ec8974a2-af80-11e6-99bc-f0a94c6a41ca.png)

**Comment by michalbcz** [comment]
fixed in 6e0059a38f440de617b647c317ead42e27796b96
