### ISSUE TITLE
Consider a sophisticated logging mechanism like http://pimterry.github.io/loglevel/

### ISSUE THREAD

**Issue by michalbcz** [realreality/reality-plugin#55]

**Comment by michalbcz** [comment]
@vire what's wrong with current logging mechanism?

**Comment by vire** [comment]
The current works on same in the same way console.log, the `prefix` is hardcoded, there are no `log-levels`, you can't turn it on except hardcoding the stuff.

Maybe it's good enough for now, but as things grow, you wanna do selective-loggin per feature you develop, or disable it at all. (now even production ext. does logging or?)

I suggested http://pimterry.github.io/loglevel/ based on experience, but if it's an overkill we can close it for now ;)

**Comment by michalbcz** [comment]
I think it's more usable in context of standard web app, but in our little extension it imho doesn't provide anything useful. I would introduce it only when we will be in need of some of the features (console polyfils, need to turn off logs in production build...etc.). Let postpone this task to that moment.
