### ISSUE TITLE
Prepare code structure to allow tests writing

### ISSUE THREAD

**Issue by bedla** [realreality/reality-plugin#59]
... and then I will write some tests :-)

**Comment by vire** [comment]
actually you can write tests right now :) I've added https://facebook.github.io/jest/ support. It's a test runner with super-powers, you just create a filename that matches the testRegex defined in `package.json` under *jest* key and then your test gets executed. Jest also provides you out-of-the-box with mocking features, so you can mock/stub browser APIs like `.fetch` to return results you can assert. In case of questions, just ask me on slack .)

**Comment by michalbcz** [comment]
@bedla wut? :)

**Comment by bedla** [comment]
could you add one sample test (right directory structure) which will be periodically started by CI server? :-)

**Comment by vire** [comment]
It's already executing a test in CI (that's the green badge in the project README on github root)

https://travis-ci.org/realreality/reality-plugin

when you execute `npm test` and it fires up the test runner and it executes everything matching the `testRegex` for example now it's just one test `src/js/sites/index.spec.js`

**Comment by krtek** [comment]
👍 
Exactly. See [https://github.com/realreality/reality-plugin/blob/master/src/js/sites/index.spec.js](index.spec.js).

**Comment by bedla** [comment]
ok, i was expecting file with "test" in file name :) thx
